config/routes.rb
Rails.application.routes.draw do
  resources :songs, only: [:index] do
    resources :likes, only: [:new, :create] 
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: :destroy

  root 'songs#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :song
  validates :song_id, :body, presence: true
  scope :recent, -> { order('created_at DESC') }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :song
  validates :song_id, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :likes
  has_many :comments
  validates :title, :embed_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :lookup_song, except: [:destroy]

  def new
    @comment = @song.comments.new
  end

  def create
    @comment = @song.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.js { }
        format.html { redirect_to root_url, notice: 'Success! We added your comment' }
      else
        format.js { }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.js { }
      format.html { redirect_to root_url, notice: 'Comment marked as spam' }
    end
  end

  private 

  def lookup_song
    @song = Song.find(params[:song_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :lookup_song, :lookup_like

  def new
  end

  def create
    respond_to do |format|
      if @like.save
        format.js { }
        format.html { redirect_to root_url, notice: 'Success! You liked the song' }
      else
        format.js { }
        format.html { render 'new' }
      end
    end
  end

  private 

  def lookup_song
    @song = Song.find(params[:song_id])
  end

  def lookup_like
    @like = @song.likes.new
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
    @like = Like.new
    @comment = Comment.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/comments/_comment.html.erb
<li class="comment-<%= comment.id %>">
    <%= comment.body %><strong> - <%= comment.created_at.to_formatted_s(:long) %> - </strong>
    <%= link_to 'Mark as spam', comment_path(comment), method: :delete, :remote => true, :class => 'delete_comment' %>
</li>

app/views/comments/_form.html.erb
<%= form_for([song, comment], remote: true) do |f| %>
  <%= f.text_area :body, class: "u-full-width comment-body" %>
  <%= f.submit 'Save', class: "button-primary" %>
<% end %>

app/views/comments/create.js.erb
$('.comments-list-<%= @comment.song_id %>').prepend('<%= j(render(@comment)) %>').fadeIn('slow');

$('.comment-body').val('');

app/views/comments/destroy.js.erb
$('.delete_comment').bind('ajax:success', function() {  
  $(this).closest('li').fadeOut();
});  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loudcloud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <header class="row">
    <div class="twelve columns">
      <h1>Loudcloud</h1>
    </div>
  </header>
  <%= yield %>
</div>
</body>
</html>

app/views/likes/_form.html.erb
<%= form_for([song, like], remote: true) do |f| %>
  <%= f.submit 'Like', class: "button-primary likes-button", :id => song.id %>
<% end %>

app/views/likes/create.js.erb
var likes = $("#likes-for-<%= @like.song_id %>").text();

$('#likes-for-<%= @like.song_id %>').text(parseInt(likes) + 1);

app/views/songs/_song.html.erb
<li class="song" id="song-<%= song.id %>">
  <h4 class="title"><%= song.title %></h4>
  <div class="player"><%= raw song.embed_code %></div> 
  <div class="likes-box">
    <div class="likes"><span id="likes-for-<%= song.id %>"><%= song.likes.count %></span>  like(s)</div>
    <div class="click-like">
      <%= render partial: "likes/form", :locals => {:song => song, :like => @like} %>
    </div>
  </div>
  <div class="comments-box">
    <ul class="comments-list-<%= song.id %>">
      <% song.comments.recent.each do |comment| %>
        <%= render comment %>
      <% end %>
    </ul>
  </div>
  <div class="comment-form">
    <p>Add a comment:</p>
    <%= render partial: "comments/form", :locals => {:song => song, :comment => @comment} %>
  </div>
</li>

app/views/songs/index.html.erb
<div class="row">
  <div class="one-half column">
    <ul class="song-list">
      <% @songs.each do |song| %>
        <%= render song %>
      <% end %>
    </ul>
  </div>
</div>